format = """
[](fg:#7aa2f7)\
$os\
[ ](fg:#7aa2f7 bg:#2f3039)\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
[](fg:#2f3039)\
$fill\
[](fg:green)\
$python\
$nodejs\
[](fg:green)\
\n$character\
"""

right_format = """
$cmd_duration
$lua
$rust
$time
"""

[os]
format = "[$symbol]($style)"
style = 'fg:#2f3039 bg:#7aa2f7'
disabled = false

[os.symbols]
Macos = "  " # nf-fa-apple
Ubuntu = "   " # nf-linux-ubuntu
Debian = "   " # nf-linux-debian

[directory]
truncation_length = 4
truncation_symbol = '  ' # nf-fa-folder_open
truncate_to_repo = false
home_symbol = ' ~' # nf-costum-home
style = 'fg:#7aa2f7 bg:#2f3039'
read_only = ' 󰌾 ' # nf-md-lock
read_only_style = 'fg:#f7768e bg:#2f3039'
format = '[$path]($style)[$read_only]($read_only_style)'

[git_branch]
symbol = '   ' # nf-fa-github_alt, nf-fa-code_fork
truncation_length = 20
truncation_symbol = '...'
style = 'fg:#7aa2f7 bg:#2f3039'
format = '[  $symbol$branch(:$remote_branch) ]($style)' # nf-pl-left_soft_divider

[git_state]
style = "yellow"


[git_status]
style = 'bg:#2f3039'
ahead = " $ahead_count "
behind = " $behind_count "
conflicted = "× "
deleted = "󰆴 $count "
diverged = "ﮙ "
format = "[$stashed](fg:cyan $style)[$conflicted$deleted](fg:red $style)[$renamed$modified](fg:#e0af68 $style)[$staged](fg:blue $style)[$untracked](fg:bright-red $style)[$ahead_behind](fg:#aaaaaa $style)"
modified = " $count "
renamed = " $count "
staged = " $count "
stashed = " $count "
untracked = "? $count "
up_to_date = " "


[git_metrics]
added_style = 'fg:#9ece6a bg:#2f3039'
deleted_style = 'fg:#9ece6a bg:#2f3039'
format = '([+$added ]($added_style))([-$deleted ]($deleted_style))'
disabled = false

[fill]
symbol = '─'
style = 'fg:#2f3039'

[python]
symbol = ' ' # nf-dev-python
format = '[ ${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)'
pyenv_version_name = false
style = 'fg:#2f3039 bg:green'

[nodejs]
symbol = ' ' # nf-dev-nodejs
format = '[ ${symbol}${version} ]($style)'
style = 'fg:#2f3039 bg:green'

[direnv]
format = '[$symbol$allowed]($style) '
style = "bold fg:#2f3039 bg:#cba6f7"
disabled = false

[character]
success_symbol = '[❯](bold #9ece6a)'
error_symbol = '[❯](bold red)'

[cmd_duration]
min_time = 1
style = 'fg:#e0af68'
format = "[   $duration]($style)" # nf-pl-right_soft_divider, nf-mdi-clock

[lua]
symbol = "" # nf-seti-lua
format = '[  $symbol $version](blue)' # nf-pl-right_soft_divider

[rust]
symbol = "" # nf-dev-rust
format = '[  $symbol $version](red)' # nf-pl-right_soft_divider

[time]
disabled = false
style = 'fg:#73daca'
format = '[   $time]($style)' # nf-pl-right_soft_divider, nf-fa-clock_o
time_format = '%T'
utc_time_offset = '+9'
